# Generated by Django 3.0.2 on 2020-01-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20, null=True)),
                ('lname', models.CharField(max_length=20, null=True)),
                ('nickname', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('music', models.FileField(upload_to='albums/%Y-%m-%d/')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_music.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_music.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('decription', models.TextField(null=True)),
                ('summery', models.CharField(max_length=100, null=True)),
                ('cover', models.ImageField(null=True, upload_to='albums/%Y-%m-%d/')),
                ('rate', models.FloatField(default=0, null=True)),
                ('release_date', models.DateField(null=True)),
                ('like', models.PositiveSmallIntegerField(default=0, null=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_music.Artist')),
            ],
        ),
    ]
