# Generated by Django 3.0.2 on 2020-01-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='fname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='lname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
