# Generated by Django 3.0.2 on 2020-01-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_music', '0002_auto_20200127_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
