# Generated by Django 3.0.2 on 2020-01-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_music', '0003_auto_20200127_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_music.Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_music.Album'),
        ),
    ]
